Wt 100 implement storing user data in firestore
Evil-Monkey-Inc/water_tracker pull request #55
Opened 2023-01-13 04:56 UTC by k1mka

2023-01-22 09:35 UTC, zddarova requested changes

2023-01-22 09:35 UTC, zddarova commented on lib/presentation/screens/greeting_screen/greeting_layout.dart
> +  final String email;
could we instead of passing email all over the screens just use inherited widget above?

2023-01-22 09:35 UTC, zddarova commented on lib/presentation/screens/greeting_screen/greeting_layout.dart
> +  final String email;
or save it to the repository and store it there? i think, this is preferable

2023-01-22 09:35 UTC, zddarova commented on lib/presentation/screens/sign_up_screen/sign_up_layout.dart
> +                      Navigator.of(context).push(MaterialPageRoute(
navigate on success state, not on button push

2023-01-22 09:35 UTC, zddarova commented
delete zip archive from project

2023-01-25 06:03 UTC, zddarova requested changes

2023-01-25 06:03 UTC, zddarova commented on lib/data/repository/repository_impl.dart
> +  late final String? _userEmail;
not final, not late, just String _userEmail.

2023-01-25 06:03 UTC, zddarova commented on lib/data/repository/repository_impl.dart
> +  RepositoryImpl(this.registrationService, this.storageService, [this._userEmail]);
remove from constructor

2023-01-25 06:03 UTC, zddarova commented on lib/data/repository/repository_impl.dart
> +  String get userEmail => _userEmail!;
no, remove null check and return nullable string

2023-01-25 06:03 UTC, zddarova commented on lib/data/repository/repository_impl.dart
> +  String get userEmail => _userEmail!;
is getter used anywhere?

2023-01-25 06:03 UTC, zddarova commented on lib/data/repository/repository_impl.dart
> +  Future<bool> registerUser(email, String password) async {
why did you removed string?

2023-01-25 06:03 UTC, zddarova commented on lib/data/repository/repository_impl.dart
> +  Future<bool> saveGeneralInfo(String email, UserSettings userSettings) async {
you don't need to pass email in every method

2023-01-25 06:03 UTC, zddarova commented on lib/data/repository/repository_impl.dart
> +  Future<bool> saveGoal(String email, GoalList goalsList) async {
you don't need to pass email in every method

2023-01-25 06:03 UTC, zddarova commented on lib/data/repository/repository_impl.dart
> +  Future<bool> saveCupCount(String email, int counterCups) async {
you don't need to pass email in every method

2023-01-25 06:03 UTC, zddarova commented on lib/data/repository/repository_impl.dart
> +  Future<int?> getCupCount(String email, DateTime time) async {
you don't need to pass email in every method

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/goal_screen/bloc/goal_bloc.dart
> +  final RepositoryImpl? repositoryImpl;
fuck no

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/goal_screen/bloc/goal_event.dart
> +  SaveGoalEvent({required this.goals});
make it only positional param, as it was

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/goal_screen/goal_layout.dart
> +                    Navigator.of(context).push(MaterialPageRoute(builder: (context) =>  const NotificationScreen()));
i thought, we removed all navigation from onPressed. Remove it too and recheck for others

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/goal_screen/goal_screen.dart
> +      child:  const GoalLayout(),
why do you keep ruining formatting like this?

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/goal_screen/goal_screen.dart
> +
why do you keep ruining formatting like this?

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/greeting_screen/greeting_screen.dart
> +
wtf

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/main_screen/bloc/main_screen_bloc.dart
> +  MainScreenBloc(this.repository, [this.repositoryImpl]) : super(CounterState(0)) {
remove

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/main_screen/bloc/main_screen_bloc.dart
> +  final RepositoryImpl? repositoryImpl;
remove

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/main_screen/bloc/main_screen_bloc.dart
> +      final result = await repository.getCupCount(repositoryImpl!.userEmail, DateTime.now());
do not pass

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/main_screen/bloc/main_screen_bloc.dart
> +        final isSaved = await repository.saveCupCount(repositoryImpl!.userEmail, newCount);
do not pass

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/main_screen/main_screen.dart
> +      child:  const MainLayout(),
wtf
remove

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/main_screen/main_screen.dart
> +
wtf
remove

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/notification_screen/notification_screen.dart
>    Widget build(BuildContext context) {
wtf
remove

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/notification_screen/notification_layout.dart
> +
wtf
remove

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/personal_settings_screen/personal_settings_layout.dart
> +                        context.read<PersonalSettingBloc>().add(SaveGeneralSettingEvent(email: widget.email, sex: gender, age: age, weight: weight)),
could you save it on sign up, not personal settings?

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/sign_in_screen/sign_in_layout.dart
> +                      Navigator.of(context).push(MaterialPageRoute(builder: (context) =>  const MainScreen()));
WTF.And use named navigation

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/sign_up_screen/bloc/sign_up_bloc.dart
> +  SignUpBloc(this.repository, [this.repositoryImpl]) : super(InitialSignUpState()) {
remove

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/sign_up_screen/bloc/sign_up_bloc.dart
> +  final RepositoryImpl? repositoryImpl;
remove

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/sign_up_screen/sign_up_layout.dart
> +                      Navigator.of(context).push(MaterialPageRoute(
comment above

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/sign_up_screen/sign_up_screen.dart
> +
stop leaving this empty lines

2023-01-25 06:03 UTC, zddarova commented on lib/presentation/screens/goal_screen/bloc/goal_bloc.dart
> +  GoalBloc(this.repository, [this.repositoryImpl]) : super(InitialGoalState()) {
remove

2023-01-25 17:39 UTC, k1mka commented on lib/data/repository/repository_impl.dart
> +  String get userEmail => _userEmail!;
Yes

2023-01-25 17:43 UTC, AndreyKomarichev10 commented on lib/data/repository/repository_impl.dart
> +  String get userEmail => _userEmail!;
but could be done without getter, just by using _userEmail field inside RepositoryImpl

2023-01-25 17:44 UTC, k1mka commented on lib/data/repository/repository_impl.dart
> +  Future<bool> saveGeneralInfo(String email, UserSettings userSettings) async {
Why?

2023-01-27 14:53 UTC, zddarova approved these changes

2023-01-27 15:05 UTC, merged